config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"

  get '/about', to: 'pages#about'

  get '/help', to: 'pages#help'

  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def help
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo_id, only: [:edit, :show, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "To-do was created successfully"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "To-do was updated successfully"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todo was destroyed successfully"
    redirect_to todos_path
  end

  private
    def todo_params
      params.require(:todo).permit(:name, :description)
    end

    def set_todo_id
      @todo = Todo.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <p><%= msg %></p>
<% end %>

app/views/layouts/_sidebar.html.erb
<p><%= link_to "Create a new Todo", new_todo_path %></p>

app/views/layouts/_title.html.erb
<h1>To-Dos</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">
  </head>

  <body>
    <div class="messages">
      <%= render 'layouts/messages' %>
    </div>

    <div class="container">
      <%= render 'layouts/title' %>

      <div class="row">
        <div class="col-xs-3 sidebar">
          <%= render "layouts/sidebar" %>
        </div>
        <div class="col-xs-9 main">
          <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello About</h1>
das ist ein test

app/views/pages/help.html.erb
<h1> Help </h1>

app/views/pages/home.html.erb
<h1>This is a To-Do App!</h1>
<h3>It is a little App I created additionally</h3>

<p>To see all Todos, please click <%= link_to "here", todos_path %></p>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h3>The following errors occurred:</h3>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@todo, :html => {class: 'form-horizontal', role: 'form'}) do |f|  %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-5">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-md-2' %>
    <div class="col-md-5">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit "Submit", class: 'btn btn-default'  %>
    </div>
  </div>
<% end %>
  <div class="col-md-offset-2 col-md-10">
    <%= link_to "Cancel", todos_path %>
  </div>

app/views/todos/edit.html.erb
<h1>Edit a To-Do</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @todos.each do |todo| %>
    <tr>
      <td> <%= todo.name %> </td>
      <td> <%= todo.description %> </td>
      <td> <%= link_to "Edit", edit_todo_path(todo) %> </td>
      <td> <%= link_to "Show", todo_path(todo) %></td>
      <td> <%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<p>
  Name: <%= @todo.name %>
</p>

<p>
  Description: <%= @todo.description %>
</p>

<%= link_to "Edit", edit_todo_path(@todo) %> |
<%= link_to "Back", todos_path %> |
<%= link_to "Delete", todo_path(@todo), method: :delete, data: {confirm: "Are you sure?"} %>